baseURL = "https://example.com/"
languageCode = "en-us"
title = "My Hugo Site"
copyright = "Copyright © 2024 John Smith"
paginate = 3

# Theme configuration
[params]
color = "SteelBlue"
width = "50%"
dateFormat = ":date_long"
mainSections = ["post"]

[params.meta]
  keywords = "blog, tech"
  description = "Professional blog."

  [params.contactForm]
    enable = true
    url = "https://formspree.io/f/mayrdroy"

  [params.commentContactForm]
    enable = true
    message = "If you found this content interesting, or have some constructive criticism please send a message using the form!"

  [params.author]
    name = "John Smith"
  [[params.social]]
    icon = "github"
    url = "https://github.com/"
    weight = "1"
  [[params.social]]
    icon = "linkedin"
    url = "https://www.linkedin.com/in/"
    weight = "2"
#  [params.comments]
#    type = "comentario"
#    url = "https://comments.example.com"

[menus]
  [[menus.main]]
    name = "About"
    url = "about/"
    weight = 1
  [[menus.main]]
    name = "Contact"
    url = "contact/"
    weight = 2
  [[menus.main]]
    name    = "Posts"
    url = "post/"
    weight = 3